### PR TITLE
Fixed z-index

### PR DESCRIPTION
**Pull request by prashantagarwal**
PR for #211

### CODE REVIEW

**Comment by vikrantnegi** [comment]
Hi,
Thanks for the PR.
I just tested this PR and found that z-index: 5 seems to fix the issue original issue but when there is a scroll bar in the editor the scrollbar seems to come on top of the console. 

Here is the screenshot:
screen shot 2017-10-04 at 11 08 16


Luckily making z-index value to 6 solved the issue. Would you mind updating the PR? 
Thanks.

**Comment by prashantagarwal** [comment]
@vikrantnegi Thanks for pointing that out. I have updated the PR.

**Comment by chinchang** [comment]
Things to test:
- All 3 layouts
- Detached mode

Hi @prashantagarwal please make sure you have tested this PR for the above mentioned test cases.

**Comment by prashantagarwal** [comment]
@chinchang Tested it, works fine in all those layouts. Though while testing I found out one more bug, that the console pane does not have an upper limit for dragging. So anyone can drag that console pane out of view. If it is intentional than cool, otherwise I will raise another PR for that.

**Comment by chinchang** [comment]
@prashantagarwal  This has broken the z-index stacking between console and footer. Remember, straightaway increasing z-index is mostly not the complete solution :)

screen shot 2017-10-13 at 10 19 11 am

**Comment by chinchang** [comment]
I fixed the footer issue. merging in 2.9.4

**Pull request merged**
