### PR TITLE
Update CoffeeScript compiler to latest CoffeeScript v2.2.1

### PR DESCRIPTION
**Pull request by nhogle**
Previous version v1.9.3 was from May 27, 2015.  Let's bring CoffeeScript to 2018! :)

FYI: I grabbed the latest compiler source from this URL:
http://coffeescript.org/v2/browser-compiler/coffeescript.js

### CODE REVIEW

**Comment by chinchang** [comment]
@nhogle Awesome!
Just for knowledge, are you using the Chrome extension or the web app?

**Comment by nhogle** [comment]
Hi Kushagra,

In my case, I was using the web app, because I was working in Mozilla
Firefox.

Cheers!

- Nick

Sent from my mobile device.

On Feb 20, 2018 9:31 PM, "Kushagra Gour" <notifications@github.com> wrote:

@nhogle <https://github.com/nhogle> Awesome!
Just for knowledge, are you using the Chrome extension or the web app?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/chinchang/web-maker/pull/266#issuecomment-367218518>,
or mute the thread

**Comment by chinchang** [comment]
For the records, coffeescript (1.9.3) was 156K and coffeescript (2.2.1) is 297K.

**Comment by chinchang** [comment]
Thanks for contributing @nhogle 👍 this will go live in 3.1.0

**Pull request merged**
