### PR TITLE
Add option to toggle faster/lighter version of extension

### PR DESCRIPTION
**Pull request by iamandrewluca**
On some machines that blur overlay just kills the performance.
Would be nice to have the option to disable it.

### CODE REVIEW

**Comment by iamandrewluca** [comment]
@chinchang any feedback here? Or should blur overlay removed completely?

**Comment by chinchang** [comment]
@iamandrewluca I am wondering if the setting should be 'Remove blur' or a general 'Switch to lighter version' sort of setting. Because this blur might now be the only thing users might be feeling slow, more things could come up in future.

Thoughts?

**Comment by iamandrewluca** [comment]
@chinchang you're right! Lighter version is better. I'll add some more commits.

**Comment by chinchang** [comment]
This is live in 2.9. Thanks for contributing @iamandrewluca :)

**Pull request merged**
