### PR TITLE
Base2Tone-Meadow scheme

### PR DESCRIPTION
**Pull request by diomed**
base2tone

### CODE REVIEW

**Comment by chinchang** [comment]
@diomed Please add code screenshots in the PR description. Excited to see this theme :)

**Comment by chinchang** [comment]
@diomed Have you deleted your repository? It shows unknown repository here.

**Comment by chinchang** [comment]
@diomed One suggestion: I think the text of normal text in HTML is very very light. It makes it very hard to read. In fact, its exactly same as comments color (which are always the lightest). I would recommend making it darker for being accessible to more number of people.

screenshot 2017-07-01 20 09 15

**Comment by diomed** [comment]
I see what you mean. 

We should try with **#47adf5** for normal text

And yeah, I'm afraid I deleted repo.  Just merge it, and modify color of first line. That'll do, I believe.

**Comment by chinchang** [comment]
Its live in 2.8.0. Thanks for contributing @diomed :)

**Pull request closed without merging**
